#!/usr/bin/env ruby

require '/home/admin/service/alert/alertstream.rb'

alert = Alert.new('/mnt/ss-shared')

video_file = alert.getvideo()

if video_file != nil
  alert.sendalert(video_file)
  begin
    alert.deletevideo(video_file)
  rescue Exception => ex
    print "An exception has occured: " + ex
  end
else 
  print "No video file found"
end
